/** The sound effects the game ships, generated by `npm run sounds`. */
export type SoundKey = 'shot' | 'hit' | 'kill' | 'hurt' | 'bargain' | 'purchase';

export const SOUND_KEYS: readonly SoundKey[] = [
  'shot',
  'hit',
  'kill',
  'hurt',
  'bargain',
  'purchase',
];
